blockful-io/swaplace-dapp

CONTRIBUTING.md
=> feat: add CONTRIBUTING.MD

components/02-molecules/NftCard.tsx, components/02-molecules/NftsList.tsx, components/02-molecules/OfferSummary.tsx, components/02-molecules/SwapStation.tsx, components/03-organisms/NftsShelf.tsx, components/03-organisms/SwappingShelfs.tsx, components/04-templates/SwapSection.tsx, lib/client/constants.ts, styles/global.css
- add empty cards in offer-sumary & nfts-list
closes #42
=> feat: add empty-cards

components/01-atoms/StatusOffers.tsx, components/01-atoms/SwappingIcons.tsx, components/01-atoms/index.ts, components/02-molecules/FilterOffers.tsx, components/02-molecules/index.tsx, components/04-templates/OfferSection.tsx, pages/swap/offers.tsx, styles/global.css
#44 
- add initial structure of offers filter
- create swap/offers page
=> feat: add swap offers filter

components/01-atoms/ConfirmSwapModal.tsx, components/01-atoms/EmptyNftsCards.tsx, components/01-atoms/SwapContext.tsx, components/01-atoms/SwapExpireTime.tsx, components/01-atoms/index.ts, components/02-molecules/NftsList.tsx, components/02-molecules/OfferSummary.tsx, components/02-molecules/SwapStation.tsx, lib/client/abi.ts, lib/client/blockchain-data.ts, lib/client/constants.ts, lib/client/utils.ts, lib/service/creatingSwap.ts, lib/wallet/wallet-config.ts
Closes #48 
- integrate the smart-contract - create-swap
- add abi
- refactor EmptyNftsCards
- add new types to use swap
- add expire-date using timestamp & selectedDate
=> feat: add create-swap

components/01-atoms/ConfirmSwapModal.tsx, components/01-atoms/SearchBar.tsx, components/01-atoms/SwapExpireTime.tsx, components/02-molecules/NftCard.tsx, components/02-molecules/OfferSummary.tsx, lib/client/abi.ts, lib/client/blockchain-data.ts, lib/service/creatingSwap.ts, lib/wallet/wallet-config.ts, styles/global.css
Closes #51 
- add select nfts n-n 
- refactor frontend v1
- remove chains ids
- adjust the select time
- add create swap  n-n
- adjust design
=> feat: add create-swap-n-n

components/01-atoms/ConfirmSwapModal.tsx, components/02-molecules/NftCard.tsx, components/02-molecules/SwapStation.tsx, lib/client/abi.ts, lib/client/blockchain-data.ts, lib/client/constants.ts, lib/service/approveSwap.ts
Closes #50 
- add MockERC721 && MockERC20 ABI
- add contract address
- add approveSwap encodedFunctionData
- update ConfirmSwapModal
#53
=> feat: add approve tokens nft

components/01-atoms/NftsCardApprovedList.tsx, components/01-atoms/SwappingIcons.tsx, components/01-atoms/Tooltip.tsx, components/01-atoms/index.ts, components/02-molecules/TheHeader.tsx
- add tooltip 
- add hover in TheHeader Icons when hovered. 
- fix NftCard Visualization in SwapConfirmationModal
closes #68
=> feat: add tooltips && adjust TheHeader icons with tooltips

components/01-atoms/index.ts
=> fix: remove unused import

components/01-atoms/SwappingIcons.tsx
=> TheHeader disabled icons improvement

components/02-molecules/TheHeader.tsx
=> add outbound link to swaplace.xyz when dApp logo is clicked #69

components/01-atoms/icons/ErrorIcon.tsx, components/01-atoms/icons/index.tsx, components/01-atoms/index.ts, components/02-molecules/ErrorFindingSwapOffers.tsx, components/02-molecules/index.tsx, components/04-templates/OfferSection.tsx, styles/global.css
Closes #97 
- add in the Offers Page the ErrorFindingSwapOffers component
=> feat: add error finding swap offers component

components/01-atoms/SearchBar.tsx
=>   feat: fix search bar lenght #125 

.env.example, lib/client/hooks/subgraphQueries.ts
=>  feat: change env variable name for more clearance #128 

components/01-atoms/StatusOffers.tsx
closes #44 
- fix FilterOptions enum
- fix OffersFilter Record
- refactor OffersFilter map
- fix component style.
=> feat: add a active status to StatusOffers atom component

components/01-atoms/ENSAvatar.tsx, components/02-molecules/AccountBalanceWalletSidebar.tsx, components/02-molecules/EnsNameAndAddressWallet.tsx, components/02-molecules/UserInfo.tsx, components/02-molecules/index.tsx, lib/client/hooks/useWalletBalance.tsx, lib/client/utils.ts
=> show wallet balance

components/02-molecules/EnsNameAndAddressWallet.tsx
=> create block explorer link

README.md
The previous README.md was not clear enough regarding the branch that we are developing. This update aims to clarify how to get started in the repository, what to do, and what not to do.
I'll also remove all the excess branches from the main repository to clarify which stage we are on.
Definition of Done:
=> docs: cleared instructions on README.md

components/01-atoms/TokensOfferSkeleton.tsx
- add TokensOfferSkeleton component
=> feat: add TokensOfferSkeleton

components/01-atoms/OfferTag.tsx
Closes #107
- add Offer Tag component
=> feat: add Offer Tag Component

components/01-atoms/SwapOfferDetails.tsx
This is the bottom of the TokenCard, which hosts information regarding the author and timestamp while allowing options to manage the Swap.
Definition of Done:
=> feat: add swap-offer details component

components/01-atoms/Tooltip.tsx
(Closes #106 🔒)
- No Pointer Events ✍️
=> refactor: tooltip adjust

components/02-molecules/OfferSummary.tsx
(Closes #146 🔒)
- Empty cards appearing all the times in SwapStation ⏹
=> fix: state of empty cards

components/02-molecules/TokenCard.tsx
=> testing duplicate card fix'

components/03-organisms/TokenOffers.tsx
=> fix icon position

components/02-molecules/TheHeader.tsx, styles/global.css
=> fix blink transition

components/02-molecules/TokenCard.tsx
=> fix light mode label

components/01-atoms/SwapModalButton.tsx, components/02-molecules/TokenAmountSelectionModal.tsx, components/02-molecules/TokenCard.tsx, components/03-organisms/ApproveTokenCard.tsx, components/03-organisms/SwapStation.tsx
=> change disabled button color
